### ISSUE TITLE
db_name疑问

### ISSUE THREAD

**Issue by it985** [GC-ZF/Twikoo-Comment-Backups#1]
1. 我的url：mongodb+srv://twikoo:pwd@cluster0.chjco7n.mongodb.net/?retryWrites=true&w=majority
2.  教程 ：得到mongodb+srv://xxx:xxx@xxx.mongodb.net/myFirstDatabase?retryWrites=true&w=majority，链接问号前的第一个字符串myFirstDatabase单独拿出来（不一定和我相同）
3. 问题：？前是mongodb+srv://twikoo:pwd@cluster0.chjco7n.mongodb.net/ 所以，db_name是twikoo还是什么

**Comment by GC-ZF** [comment]
> 1. 我的url：mongodb+srv://twikoo:[pwd@cluster0.chjco7n.mongodb.net](mailto:pwd@cluster0.chjco7n.mongodb.net)/?retryWrites=true&w=majority
> 2. 教程 ：得到mongodb+srv://xxx:[xxx@xxx.mongodb.net](mailto:xxx@xxx.mongodb.net)/myFirstDatabase?retryWrites=true&w=majority，链接问号前的第一个字符串myFirstDatabase单独拿出来（不一定和我相同）
> 3. 问题：？前是mongodb+srv://twikoo:[pwd@cluster0.chjco7n.mongodb.net](mailto:pwd@cluster0.chjco7n.mongodb.net)/ 所以，db_name是twikoo还是什么

参考https://github.com/GC-ZF/Comment-Backups/issues/3
